[package]
name = "fs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2.92"

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
